Update manage script
- Add additional functionality.

diff --git a/openshift/manage b/openshift/manage
--- a/openshift/manage
+++ b/openshift/manage
@@ -33,6 +33,18 @@ usage () {
     resetEventDatabase
       - Drop and recreate the event database.
 
+    resetMaraDatabase
+      - Drop and recreate the mara database.
+
+    deleteWallets
+      - Delete the wallets from one or more pods.
+        For example;
+          $0 -e dev deleteWallets bcreg-x-agent
+
+    recycle
+      - Recycle one or more pods.
+        For example;
+          $0 -e dev recycle mara
 EOF
 exit 1
 }
@@ -95,21 +107,51 @@ fi
 # -----------------------------------------------------------------------------------------------------------------
 # Functions:
 # -----------------------------------------------------------------------------------------------------------------
-resetEventDatabase() {
+resetDatabase() {
   _dbPodName=${1}
   if [ -z "${_dbPodName}" ]; then
-    echo -e \\n"resetEventDatabase; Missing parameter!"\\n
+    echo -e \\n"resetDatabase; Missing parameter!"\\n
     exit 1
   fi
 
-  printAndAskToContinue "If you contiune the database will be dropped and recreated.  All data will be lost."
+  printAndAskToContinue "If you contiune the ${_dbPodName} database will be dropped and recreated.  All data will be lost."
 
   switchProject
   exitOnError
 
   dropAndRecreatePostgreSqlDatabase ${_dbPodName}
 
-  echoWarning "\nThe project's database has been deleted and recreated."
+  echoWarning "\nThe ${_dbPodName} database has been deleted and recreated."
+}
+
+deleteWallets() {
+  _podNames=${@}
+  if [ -z "${_podNames}" ]; then
+    echo -e \\n"deleteWallets; Missing parameter!"\\n
+    exit 1
+  fi
+
+  printAndAskToContinue "If you contiune the wallets from ${_podNames} will be deleted.  All data will be lost."
+
+  switchProject
+  exitOnError
+
+  deleteFromPods "/home/indy/.indy_client/wallet/*" ${_podNames}
+}
+
+recycle() {
+  _pods=${@}
+  if [ -z "${_pods}" ]; then
+    echo -e \\n"recycle; Missing parameter!"\\n
+    exit 1
+  fi
+
+  switchProject
+  exitOnError
+
+  scaleDown ${_pods}
+  printAndWait "Wait for all of the pods (${_pods}) to scale down completely before continuing."
+  scaleUp ${_pods}  
 }
 # =================================================================================================================
 
@@ -121,7 +163,19 @@ case "${_cmd}" in
   reseteventdatabase)    
     # Allow all of the other parameters to be overridden ...
     dbPodName=${1:-event-db}
-    resetEventDatabase "${dbPodName}"
+    resetDatabase "${dbPodName}"
+    ;;
+  resetmaradatabase)    
+    # Allow all of the other parameters to be overridden ...
+    dbPodName=${1:-mara-db}
+    resetDatabase "${dbPodName}"
+    ;;
+  deletewallets)
+    deleteWallets ${@}
+    recycle ${@}
+    ;;
+  recycle)
+    recycle ${@}
     ;;
   *)
     echoWarning "Unrecognized command; ${_cmd}"
